default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  port: 5432

development:
  <<: *default
  database: crypto_wallet
test:
  <<: *default
  database: crypto_wallet_test
